version: '3'

services:

    docbook:
        image: phoen1x/livingfire-docbook
        # build: .
        env_file:
            - ".env"
        volumes:
            - "$PWD/book:/book"
            - "$PWD/plantuml:/plantuml"
            - "$PWD/tmp/m2:/root/.m2"
            - "$PWD/tmp/wiki:/wiki"
